// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	"github.com/stretchr/testify/mock"

	"github.com/Mellanox/ib-kubernetes/pkg/watcher"
	resEventHandler "github.com/Mellanox/ib-kubernetes/pkg/watcher/handler"
)

// Watcher is an autogenerated mock type for the Watcher type
type MockWatcher struct {
	mock.Mock
	handler resEventHandler.ResourceEventHandler
}

// NewWatcher creates a new mock Watcher with the given handler
func NewWatcher(handler resEventHandler.ResourceEventHandler) *MockWatcher {
	return &MockWatcher{
		handler: handler,
	}
}

// RunBackground provides a mock function
func (_m *MockWatcher) RunBackground() watcher.StopFunc {
	ret := _m.Called()

	var r0 watcher.StopFunc
	if rf, ok := ret.Get(0).(func() watcher.StopFunc); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(watcher.StopFunc)
		}
	}

	return r0
}

// GetHandler provides a mock function
func (_m *MockWatcher) GetHandler() resEventHandler.ResourceEventHandler {
	if _m.handler != nil {
		return _m.handler
	}

	ret := _m.Called()

	var r0 resEventHandler.ResourceEventHandler
	if rf, ok := ret.Get(0).(func() resEventHandler.ResourceEventHandler); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(resEventHandler.ResourceEventHandler)
		}
	}

	return r0
}

