// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	"net"
	"sync"

	"github.com/stretchr/testify/mock"
)

// SubnetManagerClient is an autogenerated mock type for the SubnetManagerClient type
type SubnetManagerClient struct {
	mock.Mock
	mu sync.Mutex

	// Track all GUIDs added/removed for verification
	AddedGUIDs   map[int][]net.HardwareAddr
	RemovedGUIDs map[int][]net.HardwareAddr
	AddedLimitedGUIDs map[int][]net.HardwareAddr
}

// NewSubnetManagerClient creates a new mock with initialized maps
func NewSubnetManagerClient() *SubnetManagerClient {
	return &SubnetManagerClient{
		AddedGUIDs:        make(map[int][]net.HardwareAddr),
		RemovedGUIDs:      make(map[int][]net.HardwareAddr),
		AddedLimitedGUIDs: make(map[int][]net.HardwareAddr),
	}
}

// Name provides a mock function with given fields:
func (_m *SubnetManagerClient) Name() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Spec provides a mock function with given fields:
func (_m *SubnetManagerClient) Spec() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Validate provides a mock function with given fields:
func (_m *SubnetManagerClient) Validate() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AddGuidsToPKey provides a mock function with given fields: pkey, guids
func (_m *SubnetManagerClient) AddGuidsToPKey(pkey int, guids []net.HardwareAddr) error {
	_m.mu.Lock()
	defer _m.mu.Unlock()

	ret := _m.Called(pkey, guids)

	// Track the GUIDs being added
	_m.AddedGUIDs[pkey] = append(_m.AddedGUIDs[pkey], guids...)

	var r0 error
	if rf, ok := ret.Get(0).(func(int, []net.HardwareAddr) error); ok {
		r0 = rf(pkey, guids)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AddGuidsToLimitedPKey provides a mock function with given fields: pkey, guids
func (_m *SubnetManagerClient) AddGuidsToLimitedPKey(pkey int, guids []net.HardwareAddr) error {
	_m.mu.Lock()
	defer _m.mu.Unlock()

	ret := _m.Called(pkey, guids)

	// Track the GUIDs being added as limited members
	_m.AddedLimitedGUIDs[pkey] = append(_m.AddedLimitedGUIDs[pkey], guids...)

	var r0 error
	if rf, ok := ret.Get(0).(func(int, []net.HardwareAddr) error); ok {
		r0 = rf(pkey, guids)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RemoveGuidsFromPKey provides a mock function with given fields: pkey, guids
func (_m *SubnetManagerClient) RemoveGuidsFromPKey(pkey int, guids []net.HardwareAddr) error {
	_m.mu.Lock()
	defer _m.mu.Unlock()

	ret := _m.Called(pkey, guids)

	// Track the GUIDs being removed
	_m.RemovedGUIDs[pkey] = append(_m.RemovedGUIDs[pkey], guids...)

	var r0 error
	if rf, ok := ret.Get(0).(func(int, []net.HardwareAddr) error); ok {
		r0 = rf(pkey, guids)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ListGuidsInUse provides a mock function with given fields:
func (_m *SubnetManagerClient) ListGuidsInUse() ([]string, error) {
	ret := _m.Called()

	var r0 []string
	if rf, ok := ret.Get(0).(func() []string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SetConfig provides a mock function with given fields: config
func (_m *SubnetManagerClient) SetConfig(config map[string]interface{}) error {
	ret := _m.Called(config)

	var r0 error
	if rf, ok := ret.Get(0).(func(map[string]interface{}) error); ok {
		r0 = rf(config)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAllAddedGUIDs returns all GUIDs that were added across all pkeys
func (_m *SubnetManagerClient) GetAllAddedGUIDs() []string {
	_m.mu.Lock()
	defer _m.mu.Unlock()

	var allGUIDs []string
	for _, guids := range _m.AddedGUIDs {
		for _, guid := range guids {
			allGUIDs = append(allGUIDs, guid.String())
		}
	}
	return allGUIDs
}

// GetAllRemovedGUIDs returns all GUIDs that were removed across all pkeys
func (_m *SubnetManagerClient) GetAllRemovedGUIDs() []string {
	_m.mu.Lock()
	defer _m.mu.Unlock()

	var allGUIDs []string
	for _, guids := range _m.RemovedGUIDs {
		for _, guid := range guids {
			allGUIDs = append(allGUIDs, guid.String())
		}
	}
	return allGUIDs
}

// GetAddedGUIDsForPKey returns GUIDs added to a specific pkey
func (_m *SubnetManagerClient) GetAddedGUIDsForPKey(pkey int) []string {
	_m.mu.Lock()
	defer _m.mu.Unlock()

	var guidsStr []string
	for _, guid := range _m.AddedGUIDs[pkey] {
		guidsStr = append(guidsStr, guid.String())
	}
	return guidsStr
}

// GetRemovedGUIDsForPKey returns GUIDs removed from a specific pkey
func (_m *SubnetManagerClient) GetRemovedGUIDsForPKey(pkey int) []string {
	_m.mu.Lock()
	defer _m.mu.Unlock()

	var guidsStr []string
	for _, guid := range _m.RemovedGUIDs[pkey] {
		guidsStr = append(guidsStr, guid.String())
	}
	return guidsStr
}

// Reset clears all tracked GUIDs
func (_m *SubnetManagerClient) Reset() {
	_m.mu.Lock()
	defer _m.mu.Unlock()

	_m.AddedGUIDs = make(map[int][]net.HardwareAddr)
	_m.RemovedGUIDs = make(map[int][]net.HardwareAddr)
	_m.AddedLimitedGUIDs = make(map[int][]net.HardwareAddr)
}

